# Generated by Django 4.1.2 on 2022-10-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_bookinfo_heroinfo_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='time',
        ),
        migrations.AddField(
            model_name='rules',
            name='file_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='rules',
            name='hash_value',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rules',
            name='rule',
            field=models.CharField(default='', max_length=9000),
        ),
        migrations.AddField(
            model_name='rules',
            name='state',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='rules',
            name='update_time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
